spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiry: 86400000
  refresh-token-expiry: 1209600000